# Generated by Django 2.2.4 on 2019-09-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reskey', models.CharField(max_length=200)),
                ('resadd', models.CharField(max_length=200)),
                ('resid', models.CharField(max_length=200)),
            ],
        ),
    ]
