# Generated by Django 2.2.4 on 2019-10-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_mad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MAD',
        ),
    ]
