# Generated by Django 2.2.4 on 2019-10-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_mad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MAD',
            new_name='DEMOD',
        ),
    ]
