# Generated by Django 2.2.4 on 2019-10-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20191001_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXSIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
    ]
