# Generated by Django 2.2.4 on 2019-10-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20191001_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madout',
            name='audiofreq',
            field=models.CharField(max_length=200),
        ),
    ]
