# Generated by Django 2.2.4 on 2019-10-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20191002_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madout',
            old_name='audiofreq',
            new_name='audiofreqz_Hz',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='audiolev',
            new_name='audiolev_mV',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='avepeak',
            new_name='avepeak_kHz',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='limit',
            new_name='limit_kHz',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='margin',
            new_name='margin_kHz',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='minuspeak',
            new_name='minuspeak_kHz',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='pluspeak',
            new_name='pluspeak_kHz',
        ),
    ]
