# Generated by Django 2.2.4 on 2019-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20191002_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
    ]
