# Generated by Django 2.2.4 on 2019-10-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_acp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACPOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frequency_MHz', models.CharField(max_length=200)),
                ('CarrierPower_dBm', models.FloatField(max_length=200)),
                ('ACPminus_dBc', models.FloatField(max_length=200)),
                ('ACPplus_dBc', models.FloatField(max_length=200)),
                ('TimeStamp', models.CharField(max_length=200)),
            ],
        ),
    ]
