# Generated by Django 2.2.4 on 2019-10-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_acpout'),
    ]

    operations = [
        migrations.AddField(
            model_name='acpout',
            name='Screenshot_file',
            field=models.CharField(default='hh', max_length=200),
            preserve_default=False,
        ),
    ]
