# Generated by Django 2.2.4 on 2019-10-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_cse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSEOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubRange', models.CharField(max_length=200)),
                ('CSE1_Frequency_MHz', models.FloatField(max_length=200)),
                ('CSE1_Level_dBm', models.FloatField(max_length=200)),
                ('CSE2_Frequency_MHz', models.FloatField(max_length=200)),
                ('CSE2_Level_dBm', models.FloatField(max_length=200)),
                ('limit_kHz', models.FloatField(max_length=200)),
                ('margin_kHz', models.FloatField(max_length=200)),
                ('Screenshot_file', models.CharField(max_length=200)),
            ],
        ),
    ]
