# Generated by Django 2.2.4 on 2019-10-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_rxsig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACSOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CH_Freq_MHz', models.FloatField(max_length=200)),
                ('CH_Lev_dBuV', models.FloatField(max_length=200)),
                ('IN_Freq_MHz', models.FloatField(max_length=200)),
                ('IN_Lev_dBuV', models.FloatField(max_length=200)),
                ('ACS_High_dB', models.FloatField(max_length=200)),
                ('ACS_Low_dB', models.FloatField(max_length=200)),
                ('limit_dB', models.FloatField(max_length=200)),
                ('TimeStamp', models.CharField(max_length=200)),
            ],
        ),
    ]
