# Generated by Django 2.2.4 on 2019-10-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_acsout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsout',
            old_name='ACS_High_dB',
            new_name='ACS_dB',
        ),
        migrations.RemoveField(
            model_name='acsout',
            name='ACS_Low_dB',
        ),
    ]
