# Generated by Django 2.2.4 on 2019-10-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_auto_20191021_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsout',
            old_name='timeStamp',
            new_name='TimeStamp',
        ),
        migrations.RenameField(
            model_name='madout',
            old_name='timestamp',
            new_name='Timestamp',
        ),
    ]
