# Generated by Django 2.2.4 on 2019-10-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_auto_20191021_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acsout',
            name='TimeStamp',
        ),
    ]
