# Generated by Django 2.2.4 on 2019-10-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_remove_acsout_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsout',
            name='CH_Lev_dBuV',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acsout',
            name='IN_Lev_dBuV',
            field=models.CharField(max_length=200),
        ),
    ]
