# Generated by Django 2.2.4 on 2019-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0029_auto_20191021_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsout',
            name='CH_Freq_MHz',
            field=models.CharField(max_length=200),
        ),
    ]
