# Generated by Django 2.2.4 on 2019-10-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_acsout_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madout',
            old_name='Timestamp',
            new_name='TimeStamp',
        ),
    ]
