# Generated by Django 2.2.4 on 2019-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_srout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srout',
            name='id',
        ),
        migrations.AlterField(
            model_name='srout',
            name='CH_Freq_MHz',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
