# Generated by Django 2.2.4 on 2019-10-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0036_blkout_test_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blkout',
            name='id',
        ),
        migrations.AlterField(
            model_name='blkout',
            name='Test_number',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
