# Generated by Django 2.2.4 on 2019-10-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0037_auto_20191031_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blkout',
            name='Test_number',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
