# Generated by Django 2.2.4 on 2019-10-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0038_auto_20191031_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACSOUT',
        ),
    ]
