# Generated by Django 2.2.4 on 2019-10-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0039_delete_acsout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACSOUT',
            fields=[
                ('Test_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CH_Freq_MHz', models.CharField(max_length=200)),
                ('CH_Lev_dBuV', models.CharField(max_length=200)),
                ('IN_Freq_MHz', models.FloatField(max_length=200)),
                ('IN_Lev_dBuV', models.CharField(max_length=200)),
                ('ACS_dB', models.FloatField(max_length=200)),
                ('limit_dB', models.FloatField(max_length=200)),
                ('TimeStamp', models.CharField(max_length=200)),
            ],
        ),
    ]
