# Generated by Django 2.2.4 on 2019-10-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0040_acsout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACSOUT',
        ),
    ]
