# Generated by Django 2.2.4 on 2019-10-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0042_acsout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsout',
            old_name='Test_number',
            new_name='Test_name',
        ),
    ]
