# Generated by Django 2.2.4 on 2019-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0044_auto_20191031_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsout',
            name='CH_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acsout',
            name='IN_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
    ]
