# Generated by Django 2.2.4 on 2019-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0045_auto_20191031_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blkout',
            old_name='Test_number',
            new_name='Test_name',
        ),
        migrations.AlterField(
            model_name='blkout',
            name='CH_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blkout',
            name='IN_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
    ]
