# Generated by Django 2.2.4 on 2019-10-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0046_auto_20191031_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='srout',
            name='Test_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='srout',
            name='CH_Freq_MHz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='srout',
            name='CH_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='srout',
            name='IN_Lev_dBuV',
            field=models.FloatField(max_length=200),
        ),
    ]
