# Generated by Django 2.2.4 on 2019-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0048_auto_20191031_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='madout',
            name='Test_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='madout',
            name='audiofreq_Hz',
            field=models.CharField(max_length=200),
        ),
    ]
