# Generated by Django 2.2.4 on 2019-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0050_auto_20191101_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='FETOUT',
            fields=[
                ('Test_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CH_Freq_MHz', models.CharField(max_length=200)),
                ('Freq_Error_MHz', models.FloatField(max_length=200)),
                ('Fre_error_limit_Hz', models.FloatField(max_length=200)),
                ('Power_dB', models.FloatField(max_length=200)),
                ('Power_limit_dB', models.FloatField(max_length=200)),
                ('TimeStamp', models.CharField(max_length=200)),
            ],
        ),
    ]
