# Generated by Django 2.2.4 on 2019-11-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0051_fetout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FETOUT',
            new_name='FEPOUT',
        ),
    ]
