# Generated by Django 2.2.4 on 2019-11-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0052_auto_20191104_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='fepout',
            name='Screenshot_file',
            field=models.CharField(default='', max_length=200),
        ),
    ]
