# Generated by Django 2.2.4 on 2019-11-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0053_fepout_screenshot_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fepout',
            name='Screenshot_file',
            field=models.CharField(max_length=200),
        ),
    ]
