# Generated by Django 2.2.4 on 2019-11-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0055_auto_20191104_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acpout',
            name='Test_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
