# Generated by Django 2.2.4 on 2019-11-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0056_auto_20191104_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fepout',
            old_name='Power_dB',
            new_name='Power_dBm',
        ),
        migrations.RenameField(
            model_name='fepout',
            old_name='Power_limit_dB',
            new_name='Power_limit_dBm',
        ),
    ]
