# Generated by Django 2.2.4 on 2019-11-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0058_acpout_limit_dbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acpout',
            name='limit_dBm',
            field=models.FloatField(max_length=200),
        ),
    ]
