# Generated by Django 2.2.4 on 2019-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0060_auto_20191104_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseout',
            name='TimeStamp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cseout',
            name='Test_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
