# Generated by Django 2.2.4 on 2019-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0061_auto_20191104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cseout',
            name='CH_Freq_MHz',
            field=models.CharField(max_length=200),
        ),
    ]
