# Generated by Django 2.2.4 on 2019-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0062_auto_20191104_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cshout',
            name='id',
        ),
        migrations.AddField(
            model_name='cshout',
            name='CH_Freq_MHz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cshout',
            name='Test_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
