# Generated by Django 2.2.4 on 2019-11-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0063_auto_20191105_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cshout',
            name='TimeStamp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
