# Generated by Django 2.2.4 on 2019-11-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0064_cshout_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cshout',
            name='CH_Freq_MHz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cshout',
            name='Test_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
