# Generated by Django 2.2.4 on 2019-11-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0065_auto_20191105_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSHOUT',
        ),
    ]
