# Generated by Django 2.2.4 on 2019-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0066_delete_cshout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSHOUT',
            fields=[
                ('Test_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CH_Freq_MHz', models.CharField(max_length=200)),
                ('SubRange', models.CharField(max_length=200)),
                ('CSE1_Frequency_MHz', models.FloatField(max_length=200)),
                ('CSE1_Level_dBm', models.FloatField(max_length=200)),
                ('CSE2_Frequency_MHz', models.FloatField(max_length=200)),
                ('CSE2_Level_dBm', models.FloatField(max_length=200)),
                ('limit_dBm', models.FloatField(max_length=200)),
                ('Screenshot_file', models.CharField(max_length=200)),
                ('TimeStamp', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
