# Generated by Django 2.2.4 on 2019-11-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0068_auto_20191105_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='madout',
            name='CH_Freq_MHz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
