# Generated by Django 2.2.4 on 2019-11-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0069_madout_ch_freq_mhz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SENOUT',
            fields=[
                ('Test_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CH_Freq_MHz', models.CharField(max_length=200)),
                ('CH_Lev_dBuV', models.FloatField(max_length=200)),
                ('Lev_RxPort_dBm', models.FloatField(max_length=200)),
                ('SINAD_dB', models.FloatField(max_length=200)),
                ('limit_dB', models.FloatField(max_length=200)),
                ('TimeStamp', models.CharField(max_length=200)),
            ],
        ),
    ]
